### ISSUE TITLE
Rankings bug?

### ISSUE THREAD

**Issue by bvalbo** [akaneru/rankade-js-api#1]
Hi! Awesome node js project!

It seems rankings is buggy. I used `rankade.rankings.list(subset = 'main', match = 'last', page = 1)` and got the output below.

````
.../rankade-js-api-master/node_modules/rankade-js-api/lib/errors/index.js:8
      if (errors[index] == error.response.status) {
                                          ^

TypeError: Cannot read property 'status' of undefined
    at ApiErrors.parse (.../rankade-js-api-master/node_modules/rankade-js-api/lib/errors/index.js:8:43)
    at .../rankade-js-api-master/index.js:69:35
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
````

**Comment by akaneru** [comment]
Hi @bvalbo thank you for reporting the error!
I'm checking and I will let you know soon...

Bye :)

**Comment by akaneru** [comment]
I'm here, I think you are passing a non-error object to the parse function used for error API identification.

Could you please try the following code and let me know what happens?

    rankade.rankings.list('main', 'last', 1)
      .then(success => {
        console.log("successfully retrieved rankings")
        console.log(success.data.success.data)
      }).catch(error => {

        if (error.response) {
          let errorFound = rankade.errors.parse(error)
          console.log(errorFound)
        } else {
          console.log(error)
        }

      })

Thank you!

**Comment by bvalbo** [comment]
YES! That did the trick! Now it gives correct output without complaints. Thanks alot! 😃

**Comment by akaneru** [comment]
You are welcome @bvalbo !
In the next release there will comprended a check that will throw an error if the error object to parse is not valid!

Bye :)
